package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
)

const (
	// HealthSampleDefaultLimit and HealthSampleMaxLimit clamp list reads. A table that gains a row
	// every few minutes cannot be listed unbounded the way GetVitalsRecognized lists Observations.
	HealthSampleDefaultLimit = 500
	HealthSampleMaxLimit     = 5000
)

// HealthSample is one HealthKit sample pushed by the iPhone companion app.
//
// Apple Health data is deliberately not stored as FHIR Observations. Every FHIR resource write runs
// PopulateAndExtractSearchParameters, which evaluates ~40 FHIRPath expressions in a fresh goja
// runtime; that measures at roughly one second and 133MB of allocations per resource, so a year of
// five-minute heart rate would cost more than a day of CPU. These rows are written directly.
//
// The columns mirror HealthKit's own model: HKQuantitySample and HKCategorySample are both a type
// identifier plus a value and a time range, so one table absorbs new metrics without a migration.
type HealthSample struct {
	ModelBase

	User *User `json:"user,omitempty" gorm:"-"`
	//SECURITY: UserID is set by the repository from the authenticated user, never from the request body.
	UserID uuid.UUID `json:"user_id" gorm:"not null;uniqueIndex:idx_health_sample_dedup,priority:1;index:idx_health_sample_series,priority:1"`

	// ExternalUUID is HKObject.uuid, which is stable for the life of the sample on the device, making
	// it the dedup key. An app that re-sends an overlapping window, or retries a request whose
	// response it never saw, must not produce a second row.
	ExternalUUID string `json:"external_uuid" gorm:"not null;uniqueIndex:idx_health_sample_dedup,priority:2"`

	// HKType is the raw HealthKit identifier ("HKQuantityTypeIdentifierHeartRate"), kept verbatim even
	// when this server does not recognize it, so an app that outpaces the mapping table below still
	// gets its data stored rather than dropped.
	HKType string `json:"hk_type" gorm:"not null"`
	// MetricType is the normalized name ("heart_rate", "blood_pressure_systolic"), empty when HKType
	// is not in the mapping table.
	MetricType string `json:"metric_type" gorm:"index:idx_health_sample_series,priority:2"`

	StartTime time.Time `json:"start_time" gorm:"not null;index:idx_health_sample_series,priority:3"`
	EndTime   time.Time `json:"end_time" gorm:"not null"`

	// Quantity samples carry ValueNum and Unit; category samples such as sleep analysis carry ValueText.
	ValueNum  *float64 `json:"value_num,omitempty"`
	Unit      string   `json:"unit,omitempty"`
	ValueText string   `json:"value_text,omitempty"`

	// CorrelationUUID re-pairs the samples HealthKit groups into an HKCorrelation. One blood pressure
	// reading arrives as two independent quantity samples, and without this the systolic and diastolic
	// halves of a single cuff inflation are indistinguishable from two readings a minute apart.
	CorrelationUUID string `json:"correlation_uuid,omitempty" gorm:"index"`

	SourceName     string `json:"source_name,omitempty"`
	SourceBundleID string `json:"source_bundle_id,omitempty"`
	DeviceName     string `json:"device_name,omitempty"`

	Metadata datatypes.JSON `json:"metadata,omitempty" gorm:"column:metadata;type:text;serializer:json"`
}

// HealthSyncState records how far one device has pushed each metric so a reinstalled app, or a second
// device, can resume instead of re-uploading history. Anchor is an opaque base64 HKQueryAnchor owned
// by the client; the server stores and returns it without interpreting it.
//
// There is deliberately no sample counter here. How many samples exist is a question the samples table
// itself answers exactly, and a counter maintained alongside the inserts would only be able to
// disagree with it.
type HealthSyncState struct {
	ModelBase

	User *User `json:"user,omitempty" gorm:"-"`
	//SECURITY: UserID is set by the repository from the authenticated user, never from the request body.
	UserID uuid.UUID `json:"user_id" gorm:"not null;uniqueIndex:idx_health_sync_state,priority:1"`

	// DeviceID is a stable per-install identifier generated by the app.
	DeviceID   string `json:"device_id" gorm:"not null;uniqueIndex:idx_health_sync_state,priority:2"`
	MetricType string `json:"metric_type" gorm:"not null;uniqueIndex:idx_health_sync_state,priority:3"`

	Anchor            string     `json:"anchor"`
	LastSampleEndTime *time.Time `json:"last_sample_end_time,omitempty"`
	LastSyncedAt      time.Time  `json:"last_synced_at"`

	DeviceName string `json:"device_name,omitempty"`
}

// HealthSampleQueryOptions bounds a read of health_samples. The repository clamps Limit to
// HealthSampleMaxLimit and always constrains the query to the authenticated user.
type HealthSampleQueryOptions struct {
	// MetricTypes filters to these normalized metric types; empty means all of them.
	MetricTypes []string
	// HKType filters to one raw HealthKit identifier. Used for types the mapping table does not
	// yet know, which are stored with an empty metric_type.
	HKType string
	// StartTimeAfter and StartTimeBefore bound start_time, inclusive lower and exclusive upper.
	StartTimeAfter  *time.Time
	StartTimeBefore *time.Time

	Limit  int
	Offset int
	// SortAscending orders oldest first; the default is newest first.
	SortAscending bool
}

const (
	// HealthSeriesDefaultPoints and HealthSeriesMaxPoints clamp a chart series. A five-minute heart
	// rate over 90 days is tens of thousands of samples; the browser cannot plot them raw, and the
	// list endpoint's 5,000 cap is a page size, not a chart budget.
	HealthSeriesDefaultPoints = 400
	HealthSeriesMaxPoints     = 2000
)

// HealthSeriesMode selects how QueryHealthSeries aggregates. The UI registry picks the mode so a new
// metric type can choose a chart without a server change; unknown types default to points.
const (
	HealthSeriesModePoints = "points" // one (t, v) per sample, downsampled when over MaxPoints
	HealthSeriesModeDay    = "day"    // sum value_num per UTC calendar day (step count)
	HealthSeriesModeStages = "stages" // hours of each category value per UTC day (sleep)
)

// HealthMetricSummary is the latest sample of one metric type (or one unrecognized HKType), plus how
// many rows exist. The catalog page lists these; it does not page through health_samples.
type HealthMetricSummary struct {
	MetricType  string    `json:"metric_type"`
	HKType      string    `json:"hk_type"`
	Unit        string    `json:"unit,omitempty"`
	ValueNum    *float64  `json:"value_num,omitempty"`
	ValueText   string    `json:"value_text,omitempty"`
	LatestAt    time.Time `json:"latest_at"`
	EarliestAt  time.Time `json:"earliest_at"`
	SampleCount int64     `json:"sample_count"`
	SourceName  string    `json:"source_name,omitempty"`
	DeviceName  string    `json:"device_name,omitempty"`
}

// HealthMetricsCatalog is GET /health/metrics. LastSyncedAt is the newest resume point across devices,
// so the page can say when the iPhone last pushed without a second round-trip.
type HealthMetricsCatalog struct {
	LastSyncedAt *time.Time            `json:"last_synced_at,omitempty"`
	Metrics      []HealthMetricSummary `json:"metrics"`
}

// HealthSeriesQueryOptions bounds a chart read. MetricTypes and HKType are mutually exclusive: known
// metrics filter on metric_type, unrecognized ones on the raw HealthKit identifier.
type HealthSeriesQueryOptions struct {
	MetricTypes []string
	HKType      string
	// StartTimeAfter and StartTimeBefore bound start_time, inclusive lower and exclusive upper.
	StartTimeAfter  *time.Time
	StartTimeBefore *time.Time
	MaxPoints       int
	Mode            string
}

// HealthSeriesPoint is one quantity sample (or a downsample bucket's average) on a line chart.
type HealthSeriesPoint struct {
	T time.Time `json:"t"`
	V float64   `json:"v"`
}

// HealthDailyBucket is one UTC calendar day's summed quantity, used for step count bars.
type HealthDailyBucket struct {
	Date  string  `json:"date"`
	Value float64 `json:"value"`
}

// HealthStageNight is one UTC calendar day's category durations in hours, used for sleep stage bars.
type HealthStageNight struct {
	Date   string             `json:"date"`
	Stages map[string]float64 `json:"stages"`
}

// HealthSeriesStats is min/max/avg of value_num in the queried window, before downsampling.
type HealthSeriesStats struct {
	Min *float64 `json:"min,omitempty"`
	Max *float64 `json:"max,omitempty"`
	Avg *float64 `json:"avg,omitempty"`
}

// HealthSeries is GET /health/series. Exactly one of Points, Daily, or Nights is populated, matching Mode.
type HealthSeries struct {
	MetricType  string              `json:"metric_type,omitempty"`
	HKType      string              `json:"hk_type,omitempty"`
	Unit        string              `json:"unit,omitempty"`
	Total       int64               `json:"total"`
	Downsampled bool                `json:"downsampled"`
	Points      []HealthSeriesPoint `json:"points,omitempty"`
	Daily       []HealthDailyBucket `json:"daily,omitempty"`
	Nights      []HealthStageNight  `json:"nights,omitempty"`
	Stats       *HealthSeriesStats  `json:"stats,omitempty"`
}
